theme: jekyll-theme-midnight

# Add custom CSS file
markdown: kramdown
kramdown:
  input: GFM
sass:
  style: compressed

# Optional: Site description and navigation
description: "Software Engineer By Day | AI/ML Engineer By Night"